### PR TITLE
Elaborate on `MeshSeq` innards, plus some fixes

### LINKED ISSUE #122: Provide clearer explanation of the innards of `MeshSeq` and its subclasses
Raised by @ddundo.

### PR DESCRIPTION
**Pull request by jwallwork23**
Closes #122.

@stephankramer @ddundo hopefully these commits make things somewhat clearer. Let me know if anything remains to be explained.

Turns out there was some outdated code lying around that _I think_ this fixes. Before merging, I want to add some tests to avoid it getting outdated again.

### CODE REVIEW

**Comment by stephankramer** [comment]
Hey @jwallwork23. That does make things quite a bit clearer, thanks for that! I was about to write a whole epistle on some further thoughts on the code structure, but as I was writing it I realized I need to give it some further thought :-)

**Comment by ddundo** [comment]
Thanks a lot @jwallwork23 ! This did help me find the cause of my non-unique index dependency problem (I was overwriting the name of "h" to "h_old" in Icepack, so I had 2 functions named "h_old"). Easy fix :)

But I guess my questions were more basic and related to the firedrake adjoint side of things. I have a very poor understanding of what a tape is, solve blocks, etc. and couldn't find anything about it apart from the firedrake documentation which doesn't say much

**Comment by stephankramer** [comment]
@ddundo - unfortunately this is indeed very under-documented. There is a bit of information about the interface of the adjoint on http://www.dolfin-adjoint.org/en/latest/documentation/ although it's a little outdated as it was written for the previous incantation (before pyadjoint) - in particular this bit http://www.dolfin-adjoint.org/en/latest/documentation/maths/index.html#dolfin-adjoint-mathematical-background on the general mathematical idea behind adjoints is pretty good. The general approach of the automated adjoint in dolfin-adjoint/pyadjoint is described in Farrell, Ham,Funke, & Rognes, 2013. There really isn't any documentation about the innards of the current implementation, pyadjoint, unfortunately. Happy to give you a quick intro in the office at some point...

**Comment by jwallwork23** [comment]
@ddundo Have you seen the [Jupyter notebook page](http://firedrakeproject.org/notebooks.html) on the Firedrake website? At some point I wrote one on some of these Firedrake adjoint details: https://nbviewer.org/github/firedrakeproject/firedrake/blob/master/docs/notebooks/11-extract-adjoint-solutions.ipynb.

**Comment by ddundo** [comment]
Thanks both! And thanks @stephankramer - I'd appreciate that a lot! I'll come up with specific questions and ask you in person :)

**Comment by jwallwork23** [comment]
@stephankramer @ddundo Apologies that this ended up being a decent sized PR. It would be good to get it merged, though. Please could you take a look, when convenient? Thanks!

**Comment by jwallwork23** [comment]
Thanks @stephankramer!

**Pull request merged**
